version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: geek
      POSTGRES_PASSWORD: geek
      POSTGRES_DB: gb_shop
    ports:
      - "5432:5432"
    restart: unless-stopped